---
# - name: install wordpress
#   become: true
#   hosts: wordpress
#   roles:
#     - role: install-wordpress
#
# - name: install nginx
#   become: true
#   hosts: nginx
#   roles:
#     - role: install-nginx

- name: install kafka
  become: true
  hosts: kafka
  roles:
    - role: install-kafka

- name: install elk
  become: true
  hosts: elk
  roles:
    - role: install-elk
