# ============================== Filebeat inputs ===============================

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/nginx/*.log
  fields:
     topic: 'nginx'


# ------------------------------ Kafka Output -------------------------------
output.kafka:
  hosts: ["192.168.6.3:9092"]
  topic: '%{[fields.topic]}'
  partition.round_robin:
          reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000

# ================================= Processors =================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata:
  - add_docker_metadata:
  - add_kubernetes_metadata:
