---
- name: Install nginx
  apt: name=openjdk-11-jre-headless state=present update_cache=yes

- name: Download and unpack latest kafka
  unarchive: src="https://downloads.apache.org/kafka/3.0.0/kafka_2.13-3.0.0.tgz" dest="/home/vagrant" remote_src=yes creates="/home/vagrant/kafka"

- name: Copy zookeeper.service
  copy: src="roles/install-kafka/files/zookeeper.service" dest="/etc/systemd/system/"

- name: Copy kafka.service
  copy: src="roles/install-kafka/files/kafka.service" dest="/etc/systemd/system/"

- name: Start kafka|zokeeper.service
  systemd: name={{ item }} enabled=yes state=started daemon_reload=yes
  loop:
    - zokeeper.service
    - kafka.service

- name: Create topics
  shell: {{ item }}
  loop:
    - "bin/kafka-topics.sh --create --topic nginx --partitions 2 --replication-factor 1 --bootstrap-server localhost:9092"
    - "bin/kafka-topics.sh --create --topic wordpress --partitions 2 --replication-factor 1 --bootstrap-server localhost:9092"
